import type { Entry } from './content';

// All 12 notes hardcoded. To add a new one, append to this array — the
// homepage stream, pillar pages, archive, sitemap, and adjacent-note nav
// all read from here.

export const ENTRIES: Entry[] = [
  // ============ KITCHEN ============
  {
    id: 1,
    slug: 'lamb-dumplings-preserved-lemon',
    title: 'Lamb dumplings, with preserved lemon',
    pillar: 'kitchen',
    subtitle: 'My hands needed to remember the folding.',
    excerpt:
      "Lamb and preserved lemon dumplings, folded on a Tuesday in January. The pleat is the same as my grandmother's.",
    story_body:
      "Tuesday, January. Lamb and preserved lemon, folded into thin wonton skins. The pleat is the same as my grandmother's. The kitchen smells of cumin and sesame at once. Zahra walks through, peers, says nothing, smiles.",
    has_recipe: true,
    recipe_title: 'Lamb & Preserved Lemon Dumplings',
    recipe_yield: 'about thirty · serves four',
    recipe_sections: [
      {
        label: 'Filling',
        ingredients: [
          '500g lamb shoulder, hand-minced',
          '4 spring onions, sliced thin',
          'A thumb of ginger, grated',
          '2 tbsp soy sauce',
          '1 tbsp preserved lemon paste',
          '1 tsp sesame oil',
          'A pinch of white pepper',
        ],
      },
      {
        label: 'To finish',
        ingredients: [
          'Round wonton wrappers',
          'Water for sealing',
          'Chilli oil and black vinegar',
        ],
      },
    ],
    recipe_method:
      "Mix the filling with your hands. Don't overwork it.\n\nWet the rim of a wrapper, drop a teaspoon of filling, fold to a half-moon, pleat the seam from one corner across.\n\nSteam over rolling water for eight minutes. Eat at the counter, chilli oil, black vinegar.",
    cultural_origins: ['chinese', 'moroccan'],
    season: null,
    image_prompt:
      'overhead view of folded dumplings on dark wood counter, scattered preserved lemon zest, linen cloth corner, late morning kitchen light, documentary editorial, muted color, soft natural light, low contrast, film grain, medium format, 35mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'kitchen counter, late morning',
    images: null,
    entry_date: '2026-01-14',
    published: true,
    order: 10,
    created_at: '2026-01-14T00:00:00Z',
    updated_at: '2026-01-14T00:00:00Z',
  },
  {
    id: 2,
    slug: 'first-harira-of-the-season',
    title: 'The first harira',
    pillar: 'kitchen',
    subtitle: 'Day one of Ramadan. The pot has been on since noon.',
    excerpt:
      'Lentils, chickpeas, celery leaves, cinnamon at the very end. The first harira of the season.',
    story_body:
      'The pot has been on since noon. The whole house smells of cumin and tomato and that cinnamon-at-the-end thing that only happens in Ramadan. Zahra makes hers thicker than mine. I keep adjusting toward her version, year on year. It is almost there.',
    has_recipe: true,
    recipe_title: 'Harira',
    recipe_yield: 'serves six',
    recipe_sections: [
      {
        label: 'For the pot',
        ingredients: [
          '200g brown lentils, rinsed',
          '150g chickpeas, soaked overnight',
          '1 large onion, fine-chopped',
          '4 ripe tomatoes, peeled and crushed',
          'A handful of celery leaves (not stalks)',
          'A big bunch each of coriander and parsley',
          '1 tsp cumin, 1 tsp turmeric, 1/2 tsp ground ginger',
          '1/4 tsp cinnamon, right at the end',
          'A pinch of saffron',
          'Olive oil, salt, pepper',
        ],
      },
      {
        label: 'To finish',
        ingredients: [
          '2 tbsp flour mixed with a little cold water',
          'Lemon, dates, bread, at the table',
        ],
      },
    ],
    recipe_method:
      'Sweat the onion in olive oil. Tomatoes, celery leaves, herbs, spices in — a couple of minutes until the kitchen smells ridiculous.\n\nLentils and chickpeas, water to cover (about two litres). Bring up, drop to a simmer, walk away for forty-five minutes.\n\nCinnamon now. Stream the flour-water in slowly, stirring, until it just coats a spoon. Lemon at the table.',
    cultural_origins: ['moroccan'],
    season: 'ramadan',
    image_prompt:
      'rustic moroccan harira soup in a clay bowl, steam rising, dates and bread on linen, cinnamon stick, evening kitchen light, documentary editorial photography, warm muted color, soft natural light, low contrast, film grain, medium format, 50mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'iftar table, just before the cannon',
    images: null,
    entry_date: '2026-02-28',
    published: true,
    order: 9,
    created_at: '2026-02-28T00:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 3,
    slug: 'a-jar-of-preserved-lemons',
    title: 'A jar of preserved lemons',
    pillar: 'kitchen',
    subtitle: 'Salt, lemons, time. That is the whole recipe.',
    excerpt:
      'A two-litre jar in the pantry, layered with salt and small Moroccan lemons. Six weeks until they are kind.',
    story_body:
      'Small Moroccan lemons from the souk this morning, the thin-skinned kind. Quartered through the top so they open like a flower but stay attached at the base. Pack hard with salt, jar them tight, lemon juice over. Six weeks. The pantry will smell like all the good things at once.',
    has_recipe: true,
    recipe_title: 'Preserved Lemons',
    recipe_yield: 'one two-litre jar',
    recipe_sections: [
      {
        label: 'You need',
        ingredients: [
          '10–12 small thin-skinned lemons (more if your jar is wide)',
          'A generous handful of coarse sea salt',
          'Juice of 4–5 extra lemons, to top up',
          'A clean two-litre jar with a tight lid',
        ],
      },
    ],
    recipe_method:
      'Quarter each lemon from the top, almost through, leaving the base attached. Stuff each one with salt.\n\nLayer into the jar, pressing down hard so the juice rises. Top up with extra lemon juice until the lemons are submerged.\n\nLid on. Pantry. Turn the jar upside down once a week. Six weeks before they are tender. Use the rind, not the flesh.',
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'a tall glass jar of preserved lemons on a marble counter, salt scattered, soft window light, terracotta tile, documentary editorial, muted warm color, low contrast, film grain, medium format, 50mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'pantry shelf, six weeks from now',
    images: null,
    entry_date: '2026-02-04',
    published: true,
    order: 8,
    created_at: '2026-02-04T00:00:00Z',
    updated_at: '2026-02-04T00:00:00Z',
  },
  {
    id: 4,
    slug: 'fish-from-the-mellah',
    title: 'Fish from the Mellah',
    pillar: 'kitchen',
    subtitle: 'Whatever was good this morning. A whole bream, eventually.',
    excerpt:
      'A whole bream from the Mellah souk, charmoula on the bones, a bed of preserved lemon and tomato. Forty minutes in a low oven.',
    story_body:
      'I went for sardines. Came back with a whole bream because the man at the corner stall raised his eyebrows in a particular way. Charmoula on the bones, a bed of tomato and preserved lemon, into a low oven. Forty minutes, no hurry. The kitchen smells of garlic and coriander and the sea.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'whole sea bream on a ceramic platter with charmoula, preserved lemon, tomato, fresh coriander, blue tile counter, soft afternoon light, documentary editorial, muted color, low contrast, film grain, medium format, 35mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'kitchen, just out of the oven',
    images: null,
    entry_date: '2026-04-12',
    published: true,
    order: 7,
    created_at: '2026-04-12T00:00:00Z',
    updated_at: '2026-04-12T00:00:00Z',
  },

  // ============ MOROCCO ============
  {
    id: 5,
    slug: 'cannon-at-iftar',
    title: 'The cannon, at iftar',
    pillar: 'morocco',
    subtitle: 'The minute before sunset, on the rooftop.',
    excerpt:
      'The cannon from the Koutoubia, then the spoons. Every house, all at once.',
    story_body:
      'Rooftop, the minute before sunset. The cannon from the Koutoubia. Then the spoons — every house, all at once, metal on ceramic. The whole derb smells of harira for thirty seconds. Eleven Ramadans and I still come up here for it.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: 'ramadan',
    image_prompt:
      'rooftop in marrakech medina at iftar, soft apricot evening light, koutoubia minaret distant, terracotta walls, single tagine and tea glass, documentary editorial, muted warm color, low contrast, film grain, medium format, 50mm, f/2.8 --ar 3:4',
    hero_image: null,
    hero_caption: 'rooftop, the minute before the cannon',
    images: null,
    entry_date: '2026-03-02',
    published: true,
    order: 6,
    created_at: '2026-03-02T00:00:00Z',
    updated_at: '2026-03-02T00:00:00Z',
  },
  {
    id: 6,
    slug: 'six-am-in-the-courtyard',
    title: 'Six am in the courtyard',
    pillar: 'morocco',
    subtitle: 'Bare feet, cold tiles, the chipped Hong Kong cup.',
    excerpt:
      'Six am, no fountain yet, just the birds and the muezzin. Yunnan black in a cup that has survived every move.',
    story_body:
      'Bare feet, cold tiles. No fountain yet. Just the birds and the muezzin and then quiet. The courtyard is still cool from last night. Yunnan black in the chipped Hong Kong cup. The zellige goes pink at this hour. Mine for thirty more minutes, then the house wakes up.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'courtyard of a marrakech riad before sunrise, fountain still, blue and pink zellige walls, single ceramic teacup steam rising, lemon tree corner, documentary editorial, muted blue hour color, low contrast, film grain, medium format, 35mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'courtyard, before the fountain comes on',
    images: null,
    entry_date: '2026-02-15',
    published: true,
    order: 5,
    created_at: '2026-02-15T00:00:00Z',
    updated_at: '2026-02-15T00:00:00Z',
  },
  {
    id: 7,
    slug: 'tuesday-bread-oven',
    title: 'The Tuesday bread oven',
    pillar: 'morocco',
    subtitle: 'Khobz on a wooden board, your name in flour.',
    excerpt:
      'The communal oven on the corner. Two rounds of khobz, a wooden board, your name written in flour so you get yours back.',
    story_body:
      'Tuesday is communal-oven day. Two rounds of khobz on the wooden board, my initial in flour so the boy knows whose is whose. Forty minutes later he reappears with two hot loaves wrapped in a cloth, and the whole derb is the smell of bread for an hour.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'communal bread oven in marrakech medina, wooden boards with khobz loaves dusted with flour, hands of a baker, warm orange interior light, documentary editorial, muted warm color, low contrast, film grain, medium format, 35mm, f/2.8 --ar 4:5',
    hero_image: null,
    hero_caption: 'the corner oven, late morning',
    images: null,
    entry_date: '2026-02-10',
    published: true,
    order: 4,
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 8,
    slug: 'cat-and-the-fountain',
    title: 'The cat and the fountain',
    pillar: 'morocco',
    subtitle: "Siena asleep where she shouldn't be. The cat watching.",
    excerpt:
      'The fountain talks to itself at night. The cat watches Siena from the lemon tree. A small derb truce.',
    story_body:
      'The fountain talks to itself at night. The cat is in the lemon tree, watching Siena asleep on the daybed she is not supposed to be on. They have an agreement, the two of them, that I am not part of. I let them have it. I close the kitchen and go upstairs.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'marrakech riad courtyard at night, fountain glowing softly, daybed with linen throw, lemon tree shadow, cat silhouette, candle light, documentary editorial, muted warm color, low contrast, film grain, medium format, 50mm, f/2 --ar 4:5',
    hero_image: null,
    hero_caption: 'courtyard, after the kitchen closes',
    images: null,
    entry_date: '2026-04-04',
    published: true,
    order: 3,
    created_at: '2026-04-04T00:00:00Z',
    updated_at: '2026-04-04T00:00:00Z',
  },

  // ============ TRAVEL ============
  {
    id: 9,
    slug: 'a-week-in-essaouira',
    title: 'A week in Essaouira',
    pillar: 'travel',
    subtitle: 'Three hours west, salt in the air.',
    excerpt:
      'A week in Essaouira — sardines on the grill, the wind, the same blue everywhere.',
    story_body:
      'Three hours west of Marrakech and the air goes salt. Sardines on the grill at the port, four days running. Blue boats, blue doors, blue overalls — same blue, faded the same way. Came home with sand in everything and a small jar of argan oil.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'wide shot of essaouira port at low light, blue painted fishing boats along harbour wall, white seabirds, documentary editorial, salt-flat light, slightly desaturated blues, film grain, medium format, 35mm, f/4 --ar 3:2',
    hero_image: null,
    hero_caption: 'port, late afternoon, day four',
    images: null,
    entry_date: '2026-04-08',
    published: true,
    order: 2,
    created_at: '2026-04-08T00:00:00Z',
    updated_at: '2026-04-08T00:00:00Z',
  },
  {
    id: 10,
    slug: 'three-days-in-tangier',
    title: 'Three days in Tangier',
    pillar: 'travel',
    subtitle: 'A balcony over the strait, a plate of small fish.',
    excerpt:
      'A balcony over the Strait of Gibraltar. Spain in the haze. Anchovies on toast and a glass of something cold.',
    story_body:
      'A small hotel above the medina, a balcony over the Strait. Spain in the haze if you squint. Lunch at a tile-floor place near the kasbah — a plate of fried small fish, a glass of something cold, a slice of lemon. The light here is different from Marrakech. Cooler. More Atlantic.',
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'view from a tangier balcony over the strait of gibraltar, spain faint in haze, white wall foreground, small ceramic plate of olives, documentary editorial, salt-blue color palette, low contrast, film grain, medium format, 35mm, f/4 --ar 3:2',
    hero_image: null,
    hero_caption: 'balcony, tangier, lunch',
    images: null,
    entry_date: '2026-03-22',
    published: true,
    order: 1,
    created_at: '2026-03-22T00:00:00Z',
    updated_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 11,
    slug: 'chefchaouen-in-fog',
    title: 'Chefchaouen, in fog',
    pillar: 'travel',
    subtitle: "Blue everything, and a morning that wouldn't lift.",
    excerpt:
      'Chefchaouen in February — blue walls, blue stairs, blue doors. The fog never lifted. I was glad.',
    story_body:
      "Two nights in Chefchaouen and the fog never lifted. Blue walls, blue stairs, blue doors — the whole town hand-painted into the colour of an idea. I drank mint tea on a wet step at eight in the morning and didn't see another tourist for an hour. I was glad.",
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan'],
    season: null,
    image_prompt:
      'narrow blue painted street in chefchaouen morocco in morning fog, wet stones, tea glass on a stoop, no people, documentary editorial, soft cool color, low contrast, film grain, medium format, 35mm, f/2.8 --ar 3:2',
    hero_image: null,
    hero_caption: 'morning, the upper medina',
    images: null,
    entry_date: '2026-02-19',
    published: true,
    order: 11,
    created_at: '2026-02-19T00:00:00Z',
    updated_at: '2026-02-19T00:00:00Z',
  },
  {
    id: 12,
    slug: 'high-atlas-in-spring',
    title: 'The High Atlas, in spring',
    pillar: 'travel',
    subtitle: 'Snow on the peaks, almond blossom in the valley.',
    excerpt:
      'A weekend in the High Atlas. Snow above, almond blossom below, a tagine slow on the fire.',
    story_body:
      "A weekend in a stone house in the Atlas. Snow on the peaks, almond blossom in the valley, a tagine slow on the fire. The neighbour came by with bread still warm and didn't stay long enough to be thanked. I keep thinking about the silence up there.",
    has_recipe: false,
    recipe_title: null,
    recipe_yield: null,
    recipe_sections: null,
    recipe_method: null,
    cultural_origins: ['moroccan', 'amazigh'],
    season: null,
    image_prompt:
      'high atlas valley in spring, snow capped peaks, almond trees in pink blossom, stone berber village, single woman walking, documentary editorial, muted natural color, low contrast, film grain, medium format, 35mm, f/4 --ar 3:2',
    hero_image: null,
    hero_caption: 'valley road, almond blossom',
    images: null,
    entry_date: '2026-03-14',
    published: true,
    order: 12,
    created_at: '2026-03-14T00:00:00Z',
    updated_at: '2026-03-14T00:00:00Z',
  },
];

export const SETTINGS = {
  site_title: 'Derb 37',
  site_tagline: 'a journal from a house in the medina',
  volume: 'Vol. I',
  issue: 'No. III',
  season_label: 'Spring 2026',
};
