export interface GlossaryTerm {
  id: string;
  term: string;
  arabicScript?: string;
  category: string;
  definition: string;
  context?: string;
  related?: string[];
}

export const glossaryTerms: GlossaryTerm[] = [
  // ── Food & Cooking ──
  { id: 'harira', term: 'Harira', arabicScript: 'حريرة', category: 'food', definition: 'A tomato-based soup with lentils, chickpeas, and herbs, traditionally served at iftar during Ramadan. Thickened with a flour-water mixture at the end of cooking. Celery leaves (not stalks) are essential for authentic flavour.', related: ['iftar', 'chebakia', 'Ramadan'] },
  { id: 'tagine', term: 'Tagine', arabicScript: 'طاجين', category: 'food', definition: 'Both a conical clay cooking vessel and the slow-cooked dish made inside it. The cone-shaped lid traps steam and returns moisture to the dish. Common versions include chicken with preserved lemons and olives, lamb with prunes, and kefta with eggs.', related: ['preserved-lemons', 'khlii'] },
  { id: 'couscous', term: 'Couscous', arabicScript: 'كسكس', category: 'food', definition: 'Steamed semolina grains, hand-rolled and steamed three times over vegetables and meat. Traditionally served on Fridays. Topped with seven seasonal vegetables and often finished with tfaya (caramelised onions with raisins and cinnamon).', related: ['smen', 'tfaya'] },
  { id: 'msemen', term: 'Msemen', arabicScript: 'مسمن', category: 'food', definition: 'A flaky layered flatbread made by stretching dough paper-thin on an oiled surface, folding into squares, and cooking on a flat griddle. The stretching technique creates layers similar to puff pastry. Served at breakfast with honey and butter.', related: ['baghrir'] },
  { id: 'baghrir', term: 'Baghrir', arabicScript: 'بغرير', category: 'food', definition: 'Spongy semolina pancakes with a distinctive honeycomb surface of tiny holes. The holes form during cooking and absorb honey and melted butter. A staple of Moroccan breakfast.', related: ['msemen'] },
  { id: 'pastilla', term: 'Pastilla', arabicScript: 'بسطيلة', category: 'food', definition: 'A layered pie of warqa pastry filled with pigeon or chicken, almonds, eggs, and dusted with cinnamon and powdered sugar. The sweet-savoury combination is characteristic of Moroccan cuisine. Originally from Fes.', related: [] },
  { id: 'chermoula', term: 'Chermoula', arabicScript: 'شرمولة', category: 'food', definition: 'A marinade and sauce made from fresh coriander, garlic, cumin, paprika, lemon juice, and olive oil, pounded together. Primarily used with fish, especially sardines. Applied before grilling or baking.', related: ['sardines'] },
  { id: 'preserved-lemons', term: 'Preserved lemons', category: 'food', definition: 'Lemons cured in salt for approximately three months until the rind becomes soft and translucent. The rind is used (pulp discarded) in tagines and salads. A fundamental ingredient in Moroccan cooking. The flavour is intensely salty, sour, and floral.', related: ['tagine'] },
  { id: 'smen', term: 'Smen', arabicScript: 'سمن', category: 'food', definition: 'Aged, salted butter with a pungent, almost fermented flavour similar to strong blue cheese. Stored in ceramic jars for months or years. A small amount adds deep, complex flavour to couscous, lentils, and other dishes.', related: ['couscous'] },
  { id: 'amlou', term: 'Amlou', arabicScript: 'أملو', category: 'food', definition: 'A thick paste made from roasted almonds ground with argan oil and honey. Served at breakfast as a spread. Originates from the Souss region of Morocco where argan trees grow.', related: ['argan-oil'] },
  { id: 'khlii', term: 'Khlii', arabicScript: 'خليع', category: 'food', definition: 'Dried preserved meat (beef or lamb) cooked in rendered fat with spices and stored in jars. Keeps for months without refrigeration. Traditionally used in egg tagine — shredded khlii fried with tomatoes, eggs cracked on top.', related: ['tagine'] },
  { id: 'chebakia', term: 'Chebakia', arabicScript: 'شباكية', category: 'food', definition: 'Flower-shaped fried pastry dipped in hot honey and sprinkled with sesame seeds. The dough contains orange blossom water, anise, cinnamon, and saffron. Primarily made and consumed during Ramadan, served alongside harira.', related: ['harira', 'Ramadan'] },
  { id: 'ras-el-hanout', term: 'Ras el hanout', arabicScript: 'رأس الحانوت', category: 'food', definition: 'A complex spice blend whose name means "head of the shop" — the best blend a spice merchant offers. Recipes vary widely between merchants, containing anywhere from twelve to thirty spices. No two blends are identical.', related: [] },
  { id: 'mint-tea', term: 'Atay / Mint tea', arabicScript: 'أتاي', category: 'food', definition: 'Moroccan national drink made with gunpowder green tea, a large quantity of fresh mint, and sugar. Prepared in a metal teapot, poured from a height to create foam. The first glass is poured back into the pot. The mint varies seasonally — large and pungent in summer, tighter in winter.', related: [] },
  { id: 'tfaya', term: 'Tfaya', arabicScript: 'تفاية', category: 'food', definition: 'Caramelised onions cooked slowly with raisins, cinnamon, and sometimes honey. Used as a topping for couscous, adding sweetness and depth to the dish.', related: ['couscous'] },
  { id: 'argan-oil', term: 'Argan oil', arabicScript: 'زيت أركان', category: 'food', definition: 'Oil pressed from the nuts of the argan tree, endemic to southwestern Morocco. Culinary argan oil is made from roasted nuts and has a nutty, toasted flavour. Used in amlou and as a finishing oil. The trees are a UNESCO-recognized biosphere.', related: ['amlou'] },

  // ── Places & Culture ──
  { id: 'riad', term: 'Riad', arabicScript: 'رياض', category: 'architecture', definition: 'A traditional Moroccan house built around an interior courtyard garden, typically with a fountain. The name comes from the Arabic word for garden. Riads face inward — the exterior walls are plain; all beauty is inside.', related: ['derb', 'medina'] },
  { id: 'derb', term: 'Derb', arabicScript: 'درب', category: 'architecture', definition: 'A narrow residential lane or alley in the medina, often a dead end. Each derb functions as a small neighbourhood where residents know each other. The communal bread oven (ferran) typically serves one or several derbs.', related: ['riad', 'medina', 'ferran'] },
  { id: 'medina', term: 'Medina', arabicScript: 'مدينة', category: 'architecture', definition: 'The old walled city, as distinct from the modern ville nouvelle. The Marrakech medina is a UNESCO World Heritage site. Streets are narrow and largely car-free, organised around souks, mosques, and fondouks.', related: ['derb', 'souk'] },
  { id: 'zellige', term: 'Zellige', arabicScript: 'زليج', category: 'craft', definition: 'Hand-cut geometric mosaic tilework, individually chiselled from glazed terracotta. The patterns are assembled face-down, then flipped and set in plaster. A defining element of Moroccan architecture found in riads, mosques, and fountains.', related: ['tadelakt', 'zouak'] },
  { id: 'tadelakt', term: 'Tadelakt', arabicScript: 'تدلاكت', category: 'craft', definition: 'A waterproof lime plaster traditional to Marrakech, polished with river stones and treated with olive oil soap. Creates a smooth, luminous surface. Used in bathrooms, on walls, and around fountains in riads.', related: ['zellige'] },
  { id: 'zouak', term: 'Zouak', category: 'craft', definition: 'Painted wood decoration found on ceilings, doors, and window frames in traditional Moroccan architecture. Geometric and floral patterns in rich colours — blues, reds, greens, golds. The pigments fade over time, with reds often turning pink.', related: ['zellige'] },
  { id: 'ferran', term: 'Ferran', arabicScript: 'فران', category: 'culture', definition: 'A communal bread oven serving a neighbourhood in the medina. Families prepare bread at home and carry it on wooden boards to the ferran for baking in a wood-fired oven. Each family marks their bread distinctively. A small fee is charged per loaf.', related: ['derb'] },
  { id: 'souk', term: 'Souk', arabicScript: 'سوق', category: 'culture', definition: 'An open-air marketplace or commercial quarter. The Marrakech souks are organised by trade — spices, leather, metalwork, textiles, food. The food souk is busiest early morning; by seven am the regular buyers have been and gone.', related: ['medina'] },
  { id: 'jemaa-el-fna', term: 'Jemaa el Fna', arabicScript: 'جامع الفناء', category: 'culture', definition: 'The main square of Marrakech, a UNESCO-recognised Masterpiece of Oral and Intangible Heritage. By day: orange juice stalls, snake charmers. By night: dozens of food stalls with numbered stations serving grilled meats, harira, snail soup, fried fish, and fresh bread. The smoke from the grills is visible from surrounding rooftops.', related: ['harira'] },
  { id: 'mashrabiya', term: 'Mashrabiya', arabicScript: 'مشربية', category: 'architecture', definition: 'Carved wooden lattice screen used in traditional architecture. Allows air circulation and filtered light while maintaining privacy. Creates geometric shadow patterns on interior surfaces, particularly striking in early morning light.', related: ['riad'] },
  { id: 'kanoun', term: 'Kanoun', arabicScript: 'كانون', category: 'food', definition: 'A small portable clay charcoal brazier used for grilling on terraces and rooftops. The traditional cooking vessel for grilled sardines, kebabs, and other items requiring direct charcoal heat.', related: ['chermoula'] },

  // ── Ramadan ──
  { id: 'iftar', term: 'Iftar', arabicScript: 'إفطار', category: 'culture', definition: 'The evening meal that breaks the daily fast during Ramadan. In Marrakech, signalled by a cannon fired from the Koutoubia mosque. The traditional iftar spread includes harira, dates, chebakia, hard-boiled eggs, and bread.', related: ['harira', 'chebakia', 'Ramadan'] },
  { id: 'ramadan', term: 'Ramadan', arabicScript: 'رمضان', category: 'culture', definition: 'The ninth month of the Islamic calendar, observed as a month of fasting from dawn to sunset. In the Marrakech medina, the daily rhythm shifts entirely — quiet streets before iftar, bustling energy after. Special foods and sweets appear only during this month. Plates of food are passed between neighbouring houses.', related: ['iftar', 'harira', 'chebakia'] },
];
